[package]
name = "ebook-sorter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
comfy-table = "7.1.3"
epub = "2.1.2"
eyre = "0.6.12"
indicatif = "0.17.9"
prettytable-rs = "0.10.0"
thiserror = "2.0.9"
walkdir = "2.5.0"
